steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Step 2: Run setup script
  - name: 'node:18'
    entrypoint: bash
    args: ['setup.sh']
    env:
      - 'DEBIAN_FRONTEND=noninteractive'

  # Step 3: Build APK
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['assembleRelease']
    dir: 'android/app'
    env:
      - 'JAVA_TOOL_OPTIONS=-XX:MaxHeapSize=8g'

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-apk-builds'
    paths:
      - 'android/app/build/outputs/apk/release/app-release.apk'

timeout: '3600s'
